- src/components/util/CollectedBadges.vue
- src/components/views/DefaultView.vue
- src/interfaces/models.ts
- src/repositories/UserRepository.ts
* Made CollectedBadges.vue only render the badges for the given topic
* Added a heading for the CollectedBadges view
Should address #11
> Added badge category

- README.md
Changed RiPLE to RiPPLE
Should fix #26
> Updated name of project

- src/components/questions/QuestionBrowser.vue
- src/components/questions/QuestionSearch.vue
- src/repositories/BadgeRepository.ts
- src/repositories/QuestionRepository.ts
- src/repositories/UserRepository.ts
- src/services/QuestionService.ts
* Added pagination component to `QuestionBrowser` page.
* Fixed circular component updating for question pages
* Moved result calculation to happen on the server
Close #70
> Ripple #70

- src/Main.vue
- src/services/Fetcher.ts
Implemented a 10 second timeout for requests. This has significantly improved performance.
> Implemented data caching for #88

- src/Main.vue
- src/components/admin/AdminView.vue
- src/components/charts/VariableDataVisualiser.vue
- src/components/error/ErrorPermission.vue
- src/components/profile/ProfileView.vue
- src/components/questions/QuestionResponse.vue
- src/components/util/Notifications.vue
- src/interfaces/models.ts
- src/repositories/UserRepository.ts
- src/routes/index.ts
- src/services/Fetcher.ts
Implemented aesthetic changes to deal with no notifications;  #57 goes into details
> Ripple #57

- src/Main.vue
- src/components/admin/AdminView.vue
- src/components/error/ErrorPermission.vue
- src/routes/index.ts
- src/services/Fetcher.ts
Two stones with one bird for this one - implemented programmatic navigation as per explained in #89 and #85
> Ripple #89

- src/Main.vue
- src/components/admin/AdminView.vue
- src/components/error/ErrorPermission.vue
- src/components/questions/QuestionResponse.vue
- src/routes/index.ts
- src/services/Fetcher.ts
Small patches to the way vue adds content onto the page. Primarily usage of the v-html="" directive instead of `{{ data.content }}` to address #82
> Ripple #82

- client/src/components/charts/VariableDataVisualiser.vue
- client/src/components/profile/ProfileView.vue
The `VariableDataVisualiser` component can now be customized to restrict visualizations as per #96
> Added optional whitelist for `VariableDataVisualiser` to address #96.

- client/src/components/leaderboard/LeaderBoard.vue
- client/src/interfaces/models.ts
- client/src/repositories/UserRepository.ts
- client/src/services/UserService.ts
- server/src/questions/services/QuestionService.py
- server/src/questions/urls.py
- server/src/questions/views.py
Added service and repository abstraction for leaderboard and engagement data consuming for #95
> Ripple #95

- client/src/components/questions/QuestionBrowser.vue
- server/src/questions/services/SearchService.py
#133 Changed how the questions are filtered.
Previously toggling arrays off removes ALL array questions. Suppose a variable question was toggle on, then a question with both array and variable will be removed from sight.
> Modified query to distinct the values

- client/src/components/questions/QuestionBrowser.vue
- client/src/components/questions/QuestionResponse.vue
- server/src/recommendations/views.py
* Tidied up questionresponse view.
* Fixed overflowing content in the question viewer.
> Addressed changes for #146

- server/src/recommendations/views.py
- server/src/ripple/settings.py
- server/src/users/services/UserService.py
> Ripple #112

- client/src/components/author/AuthorView.vue
- client/src/components/questions/Question.vue
- client/src/components/questions/QuestionBrowser.vue
- client/src/components/questions/QuestionDetails.vue
- client/src/components/questions/QuestionPreview.vue
- client/src/interfaces/models.ts
- client/src/repositories/QuestionRepository.ts
- client/test/unit/spec/QuestionCard.spec.ts
- server/.gitignore
- server/src/questions/models.py
- server/src/ripple/management/commands/seed.py
- server/src/ripple/management/commands/seedCourse.py
> Ripple #159

- server/src/questions/services/QuestionService.py
just raised an exception when question course and user course do not match
> fixed user being able to answer separate course question bug

- client/src/services/AuthorService.ts
> fixed text in #176

- client/src/Main.vue
- client/src/components/peers/RecommendationSearch.vue
- client/src/components/profile/Competencies.vue
- client/src/components/profile/Engagement.vue
- client/src/routes/index.ts
merged the answer and author tabs into a questions submenu, also changed the icon to be more related. 
Changed the design of the tabs in connect. Changed the focus functionality so that the submenu button is not focused when the submenu links are clicked
> Ripple #183

- server/deploy.sh
- server/src/ripple/management/commands/seed.py
- server/src/ripple/management/commands/seedCourse.py
Addresses changes outlined in #172
> Ripple #172

- client/src/components/charts/VariableDataVisualiser.vue
- client/src/components/questions/QuestionBrowser.vue
- client/src/components/questions/QuestionSearch.vue
- client/src/components/util/TinyMCE.vue
- client/src/repositories/QuestionRepository.ts
- client/src/services/QuestionService.ts
- server/src/questions/urls.py
- server/src/questions/views.py
* Removed unused code in server
* Fixed question pagination
* Decoupled topic filtering and question searching from the datavis component
* Fixed spelling mistake
* Fixed layout thrashing bug caused by the Vue TinyMCE component
> Fixes to address #193

- client/src/Main.vue
- client/src/components/UserContainer.vue
Small code cleanup and added more target refresh user profile image for #195
> RIPPLE-#195

- server/requirements.txt
- server/src/questions/services/AuthorService.py
- server/src/questions/tests/common.py
- server/src/questions/tests/test_question_requests.py
Coverage for the author service. It deals with the question editor and includes code checking for specific tags, so it will have to be revisited based on the decision for #205
> Test coverage for author service

- client/src/components/util/AdminButtons.vue
> AdminButton size fixed on edit page

- client/src/components/util/Notifications.vue
- client/src/interfaces/models.ts
- client/src/repositories/UserRepository.ts
- client/src/util.ts
- server/src/users/models.py
- server/src/users/urls.py
- server/src/users/views.py
As per title.
Date display updated to DD-MM-YYYY from YYYY-MM-DD
> Notification linked to back end

- client/src/components/leaderboard/LeaderBoard.vue
- client/src/interfaces/models.ts
- server/src/questions/services/QuestionService.py
- server/src/questions/tests/common.py
- server/src/questions/tests/test_leaderboard.py
- server/src/questions/views.py
Leaderboard component + server updated to deal with new columns.
Two leaderboard queries written in rawSQL rather than django ORM due to complexity of query.
> Leaderboard modified to new columns

- .gitignore
- client/package-lock.json
- client/src/Main.vue
- client/src/components/author/AuthorView.vue
- client/src/components/author/AuthorWrapper.vue
- client/src/components/util/AdminButtons.vue
- client/src/components/util/ResponsiveWrapper.vue
- client/src/components/util/TopicChip.vue
- client/src/routes/index.ts
- client/src/routes/links.ts
- server/src/users/middleware.py
Fixed scrolling on the side menu on small screens. Also added fixed to page menu functionality to the admin buttons plus responsiveness to disable it on mobile. Also Added closing X on mobile menu as per feedback.
> Scrolling functionality on sidemenu for mobile plus other UX fixes

- client/src/components/admin/AdminView.vue
- client/src/components/author/AuthorWrapper.vue
- client/src/components/leaderboard/LeaderBoard.vue
- client/src/interfaces/models.ts
- client/src/repositories/UserRepository.ts
- client/src/services/UserService.ts
- server/src/lti/services/LTIService.py
- server/src/lti/views.py
- server/src/questions/services/QuestionService.py
- server/src/questions/tests/common.py
- server/src/questions/tests/test_leaderboard.py
- server/src/questions/views.py
- server/src/ripple/management/commands/seedCourse.py
- server/src/ripple/settings.py
- server/src/users/services/UserService.py
- server/src/users/tests/test_user_service.py
- server/src/users/urls.py
- server/src/users/views.py
Includes updates to admin downloading
1. Download "results" data for things like grade allocation
2. Download anon. "consented student" data for use in studies
> Admin downloads

- client/src/repositories/APIRepository.ts
- server/src/questions/services/AuthorService.py
- server/src/questions/views.py
- server/src/ripple/management/commands/seedCourse.py
- server/src/ripple/settings.py
- server/src/ripple/urls.py
- server/src/ripple/util/util.py
- server/src/users/middleware.py
- server/src/users/services/UserService.py
- server/src/users/tests/test_user_service.py
- server/src/users/views.py
* Updated `wiki` to remove the `FORCE_SCRIPT_NAME` param.
* Removed the `FORCE_SCRIPT_NAME` option from the application - it is not needed with the correct nginx configuration
* Made LTI be the root address.
> Removed force script name & fixed LTI root for #273

- client/src/components/profile/ConsentFormWrapper.vue
- server/src/ripple/util/util.py
- server/src/users/services/UserService.py
> Ripple #290

- client/src/components/util/TopicChip.vue
> Fix Topic Hover Colors

- server/src/users/services/UserService.py
> Fix same topics, diferent course

- server/src/questions/services/QuestionService.py
> Update base competency to 50%

- client/src/components/admin/AdminView.vue
Resolves #296 
Resolves #295 
fixes some workflow issues too
> Update Admin Page Workflow

- client/src/components/questions/QuestionSearch.vue
- client/src/repositories/UserRepository.ts
> Set default earch to recommended+unanswered

- client/src/components/questions/Question.vue
> Fix next question behaviour

- client/src/Main.vue
- client/src/main.ts
- client/src/routes/index.ts
- server/src/ripple/management/commands/seedCourse.py
- server/src/users/services/TokenService.py
- server/src/users/urls.py
- server/src/users/views.py
> Add demo admin

- server/deploy.sh
> Deploy script to use python3

- client/src/components/author/AuthorView.vue
> Fix Padding issues on smaller screens (question)

- client/src/components/UserContainer.vue
> Fix max-width course picker
